name: conda build

on: 
  push:
    branches:
      - development

jobs:
  build:
    name: Ubuntu Conda Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialise Conda
        run: |
            conda init "$(basename ${SHELL})"
      - name: Deploy Conda package
        run: |
            source /usr/share/miniconda/etc/profile.d/conda.sh
            conda create -n test --channel conda-forge conda-build anaconda-client conda-verify
            conda activate test
            conda-build recipe
