name: conda build

on: 
  push:
    branches:
      - development

jobs:
  build:
    name: Python ${{ matrix.python-version }} example
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          activate-environment: petsc
          python-version: ${{ matrix.python-version }}
          channels: underworldcode, anaconda, conda-forge
      - name: Initialise Conda
        shell: bash -l {0}
        run: conda install --channel conda-forge conda-build
      - name: Deploy Conda package
        run: conda-build recipe
